spring:
  jpa:
    show-sql : true
  messages:
    basename: esakki
      
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5innoDBDialect
        
