spring:
  jpa:
    show-sql : true
  messages:
    basename: esakki
      
    hibernate:
      ddl-auto: create
      
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
        
